version: '1'

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    env_file:
      - gitea.env
    volumes:
      - gitea-data:/data
    environment:
      - USER_UID=${USER_UID}
      - USER_GID=${USER_GID}
    ports:
      - "5123:3000"   # Web UI
      - "2222:22"     # SSH for Git
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: gitea-db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - gitea.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=gitea
    volumes:
      - gitea-db:/var/lib/mysql

volumes:
  gitea-data:
  gitea-db:
