services:

  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginxpm
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped
    ports:
      - '80:80'   # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81'   # Admin Web Port
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt

  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz
    container_name: netbootxyz
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MENU_VERSION=2.0.47 # optional
      - NGINX_PORT=80       # optional
      - WEB_APP_PORT=3000   # optional
    volumes:
      - ${USERDIR}/docker/netboot/config:/config # optional
      - ${USERDIR}/docker/netboot/assets:/assets # optional
    ports:
      - '3000:3000' # optional, destination should match ${WEB_APP_PORT} variable above.
      - '69:69/udp'
      - '8080:80'   # optional, destination should match ${NGINX_PORT} variable above.
    restart: unless-stopped
