name: Validate Docker Compose Files

on:
  push:
    paths:
      - '**/*.yml'
  pull_request:
    paths:
      - '**/*.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate Docker Compose Files
        run: |
          for file in $(find . -name 'docker-compose.yml'); do
            echo "Validating $file"
            docker compose -f "$file" config
          done
