name: Validate Docker Compose Files

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Compose CLI
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Validate each docker-compose.yml
        run: |
          for file in $(find . -name '*-stack.yml'); do
            echo "Validating $file"
            docker-compose -f "$file" config
          done
